export const getTranscriptionErrorMovie=({status_code})=> errorCodeMovie[status_code].message;

const errorCodeMovie={
"1": { httpCode: 200, message: "Éxito."},
"2": { httpCode: 501, message: "Servicio inválido: este servicio no existe."},
"3": { httpCode: 401, message: "Error de autenticación: no tiene permisos para acceder al servicio."},
"4": { httpCode: 405, message: "Formato no válido: este servicio no existe en ese formato."},
"5": { httpCode: 422, message: "Parámetros no válidos: los parámetros de su solicitud son incorrectos."},
"6": { httpCode: 404, message: "ID no válido: el ID de requisito previo no es válido o no se encuentra."},
"7": { httpCode: 401, message: "Clave de API no válida: se le debe otorgar una clave válida."},
"8": { httpCode: 403, message: "Entrada duplicada: los datos que intentó enviar ya existen."},
"9": { httpCode: 503, message: "Servicio fuera de línea: este servicio está temporalmente fuera de línea, inténtelo de nuevo más tarde."},
"10": { httpCode: 401, message: "Clave de API suspendida: se ha suspendido el acceso a su cuenta, comuníquese con TMDB."},
"11": { httpCode: 500, message: "Error interno: algo salió mal, comuníquese con TMDB."},
"12": { httpCode: 201, message: "El artículo/registro se actualizó correctamente."},
"13": { httpCode: 200, message: "El elemento/registro se eliminó con éxito."},
"14": { httpCode: 401, message: "La autenticación falló."},
"15": { httpCode: 500, message: "Ha fallado."},
"16": { httpCode: 401, message: "Dispositivo denegado."},
"17": { httpCode: 401, message: "Sesión denegada."},
"18": { httpCode: 400, message: "Validación fallida."},
"19": { httpCode: 406, message: "Encabezado de aceptación no válido."},
"20": { httpCode: 422, message: "Intervalo de fechas no válido: debe ser un intervalo de no más de 14 días."},
"21": { httpCode: 200, message: "Entrada no encontrada: no se puede encontrar el elemento que está tratando de editar."},
"22": { httpCode: 400, message: "Página no válida: las páginas comienzan en 1 y tienen un máximo de 1000. Se espera que sean un número entero."},
"23": { httpCode: 400, message: "Fecha no válida: el formato debe ser AAAA-MM-DD."},
"24": { httpCode: 504, message: "Se agotó el tiempo de espera de su solicitud al servidor backend. Intentar otra vez."},
"25": { httpCode: 429, message: "Su recuento de solicitudes (#) supera el límite permitido de (40)."},
"26": { httpCode: 400, message: "Debe proporcionar un nombre de usuario y una contraseña."},
"27": { httpCode: 400, message: "Demasiados anexos a los objetos de respuesta: el número máximo de llamadas remotas es 20."},
"28": { httpCode: 400, message: "Zona horaria no válida: consulte la documentación para conocer una zona horaria válida."},
"29": { httpCode: 400, message: "Debe confirmar esta acción: proporcione un parámetro confirm=true."},
"30": { httpCode: 401, message: "Nombre de usuario y/o contraseña no válidos: no proporcionó un inicio de sesión válido."},
"31": { httpCode: 401, message: "Cuenta deshabilitada: Su cuenta ya no está activa. Póngase en contacto con TMDB si se trata de un error."},
"32": { httpCode: 401, message: "Correo electrónico no verificado: Su dirección de correo electrónico no ha sido verificada."},
"33": { httpCode: 401, message: "Token de solicitud no válido: el token de solicitud está vencido o no es válido."},
"34": { httpCode: 404, message: "No se pudo encontrar el recurso que solicitó."},
"35": { httpCode: 401, message: "Simbolo no valido."},
"36": { httpCode: 401, message: "El usuario no ha concedido permiso de escritura a este token."},
"37": { httpCode: 404, message: "No se pudo encontrar la sesión solicitada."},
"38": { httpCode: 401, message: "No tienes permiso para editar este recurso."},
"39": { httpCode: 401, message: "Este recurso es privado."},
"40": { httpCode: 200, message: "Nada que actualizar."},
"41": { httpCode: 422, message: "Este token de solicitud no ha sido aprobado por el usuario."},
"42": { httpCode: 405, message: "Este método de solicitud no es compatible con este recurso."},
"43": { httpCode: 502, message: "No se pudo conectar con el servidor backend."},
"44": { httpCode: 500, message: "La identificación no es válida."},
"45": { httpCode: 403, message: "Este usuario ha sido suspendido."},
"46": { httpCode: 503, message: "La API está en mantenimiento. Vuelva a intentarlo más tarde."},
"47": { httpCode: 400, message: "La entrada no es válida."},
};